FROM python:3.12-slim

WORKDIR /app

# Nainstaluj systémové závislosti pro pyodbc
RUN apt-get update && apt-get install -y gcc g++ unixodbc-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:$PORT", "app:app"]
